Content-Type: multipart/alternative;
 boundary="------------7JAjZi7zQM7MkX5MeYOSK14s"
Message-ID: <6f2054a4-576d-49a7-bdfe-a67e3e0f3b0e@fuck.fuck>
Date: Sun, 19 Nov 2023 21:40:00 +0700
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Subject: Re: test advance
Content-Language: en-US
From: nguyen quang thong <fuck@fuck.fuck>
To: anhvu@fuck.fuck
References: <12f60bef-789e-48a9-8874-1fbe61f5a327@fuck.fuck>
In-Reply-To: <12f60bef-789e-48a9-8874-1fbe61f5a327@fuck.fuck>

This is a multi-part message in MIME format.
--------------7JAjZi7zQM7MkX5MeYOSK14s
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit

fuck you


On 11/13/23 09:34, nguyen quang thong wrote:
>
> *Bold
> *
>
> */Italic
> /*
>
>
>   */Heading 1/*
>
>
> Different font
>
>
> Red
>
--------------7JAjZi7zQM7MkX5MeYOSK14s
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  </head>
  <body>
    <p>fuck you</p>
    <p><br>
    </p>
    <div class="moz-cite-prefix">On 11/13/23 09:34, nguyen quang thong
      wrote:<br>
    </div>
    <blockquote type="cite"
      cite="mid:12f60bef-789e-48a9-8874-1fbe61f5a327@fuck.fuck">
      <meta http-equiv="content-type" content="text/html; charset=UTF-8">
      <p><b>Bold<br>
        </b></p>
      <p><b><i>Italic<br>
          </i></b></p>
      <h1><b><i>Heading 1</i></b></h1>
      <p><br>
      </p>
      <p><font face="Courier New, Courier, monospace">Different font</font></p>
      <p><br>
      </p>
      <p><font color="#ff0000">Red</font><br>
      </p>
    </blockquote>
  </body>
</html>

--------------7JAjZi7zQM7MkX5MeYOSK14s--
